from ai_lern_walk_android_spezial import (
    get_status,
    run_epoch,
    reset_training,
    get_visual_frame,
    reset_visualization,
    get_template_frame,
    template_add_node,
    template_add_bone,
    template_add_muscle,
    template_add_muscle_by_nodes,
    template_auto_muscles,
    template_clear,
    template_default,
    template_save,
    template_load,
    template_list,
)
